Update snyk.yml

diff --git a/.github/workflows/snyk.yml b/.github/workflows/snyk.yml
--- a/.github/workflows/snyk.yml
+++ b/.github/workflows/snyk.yml
@@ -17,7 +17,12 @@ jobs:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       - name: auth
         run: snyk auth ${{ secrets.SNYK_TOKEN }}
-      
+
+       # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
+       # Use || true to not fail the pipeline.
+      - name: Snyk IaC test and report
+        run: snyk iac test --report # || true
+        
       - name: Snyk Code test
         #run: snyk test --all-projects --org=aef0364d-d779-4277-a254-86c9a1273e6c
         run: snyk code test 
